services:
  valkey:
    container_name: nextcloud-valkey
    image: valkey/valkey:9.1.0-alpine3.23
    restart: unless-stopped

  nextcloud:
    container_name: nextcloud
    image: nextcloud:33.0.1-apache
    restart: unless-stopped
    depends_on:
      - db
      - valkey
    volumes:
      - type: bind
        source: ${NEXTCLOUD_VOLUME_PATH:?}
        target: /var/www/html
        bind:
          create_host_path: false
    environment:
      - TZ=${TIMEZONE:?}
      - REDIS_HOST=valkey
      - POSTGRES_HOST=db
      - TRUSTED_PROXIES=${NEXTCLOUD_TRUSTED_PROXIES:?}
      - OVERWRITEPROTOCOL=https
      - OVERWRITECLIURL=https://${NEXTCLOUD_DOMAIN:?}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`${NEXTCLOUD_DOMAIN:?}`)"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"

  nextcloud-cron:
    container_name: nextcloud-cron
    image: nextcloud:33.0.1-apache
    restart: unless-stopped
    depends_on:
      - db
      - valkey
    volumes:
      - type: bind
        source: ${NEXTCLOUD_VOLUME_PATH:?}
        target: /var/www/html
        bind:
          create_host_path: false
    entrypoint: /cron.sh
