repos:
  # prek builtin hooks: https://prek.j178.dev/builtin/#2-explicit-builtin-repository
  - repo: builtin
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-json5
      - id: pretty-format-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.25
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.7
    hooks:
      - id: uv-lock

  - repo: https://github.com/crate-ci/typos
    rev: v1.45.1
    hooks:
      - id: typos

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.37.1
    hooks:
      - id: check-github-workflows
        args: ["--verbose"]
      - id: check-compose-spec
        args: ["--verbose"]
      - id: check-renovate
        args: ["--verbose"]
        additional_dependencies: ['json5']

  - repo: https://github.com/aristanetworks/j2lint
    rev: v1.2.0
    hooks:
      - id: j2lint
        args: [--ignore, jinja-statements-delimiter, jinja-statements-indentation, --]
        exclude:
          glob:
            - "template/README.md.jinja"

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.13.1-1
    hooks:
      - id: shfmt
        args: [--indent, "2"]

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
        exclude:
          glob:
            - "*.sh.jinja"

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
        args: [--strict]

  - repo: https://github.com/executablebooks/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
        language: python
        args: [--number]

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.22.0
    hooks:
      - id: markdownlint-cli2

  # zizmor detects security vulnerabilities in GitHub Actions workflows.
  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: v1.24.1
    hooks:
      - id: zizmor

  # actionlint for verifying correct syntax in GitHub Actions workflows.
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.12
    hooks:
      - id: actionlint
        language: golang
        additional_dependencies:
          # actionlint has a shellcheck integration which extracts shell scripts in `run:` steps from GitHub Actions
          # and checks these with shellcheck.
          # see also: https://github.com/rhysd/actionlint/pull/482
          - "github.com/wasilibs/go-shellcheck/cmd/shellcheck@v0.11.1"

  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 43.141.2
    hooks:
      - id: renovate-config-validator
        stages:
          - manual
        args: ["--strict"]
        files: ".*\\.json5$"
