# https://copier-template-tester.kyleking.me/#configuration-file
# minimal defaults required to generate a project
[defaults]
_pre_tasks = [
    "tests/check_missing_envs.sh",
    "tests/check_missing_paths.sh",
]
test = true
letsencrypt_challenge = "tls"
letsencrypt_email = "foo@bar.baz"

[output.".ctt/defaults"]
_post_tasks = [
    "! ls .envs/letsencrypt.env",
    "! ls compose.*.yaml",
    "docker compose config --format json | jq --exit-status '.services | length == 1'",
    "docker compose config --format json | jq --exit-status '.services[\"traefik\"] | .container_name == \"traefik\"'",
    "prek run --files ./*.*",
]

[output.".ctt/no_test"]
test = false
_pre_tasks = []
_post_tasks = [
    "! ls tests/",
]

[output.".ctt/dns_challenge"]
letsencrypt_challenge = "dns"
_post_tasks = [
    "ls .envs/letsencrypt.env",
    "docker compose config --format json | jq --exit-status '.services | length == 1'",
    "docker compose config --format json | jq --exit-status '.services[\"traefik\"] | .container_name == \"traefik\"'",
    "prek run --files ./*.*",
]

[output.".ctt/pihole"]
use_pihole = true
_post_tasks = [
    "docker compose config --format json | jq --exit-status '.services | length == 2'",
    "docker compose config --format json | jq --exit-status '.services[\"pihole\"] | .container_name == \"pihole\"'",
    "prek run --files ./*.*",
]

[output.".ctt/nextcloud"]
use_nextcloud = true
_post_tasks = [
    "docker compose config --format json | jq --exit-status '.services | length == 5'",
    "docker compose config --format json | jq --exit-status '.services[\"nextcloud\"] | .container_name == \"nextcloud\"'",
    "docker compose config --format json | jq --exit-status '.services[\"db\"] | .container_name == \"db\"'",
    "prek run --files ./*.*",
]

[output.".ctt/forgejo"]
use_forgejo = true
_post_tasks = [
    "docker compose config --format json | jq --exit-status '.services | length == 3'",
    "docker compose config --format json | jq --exit-status '.services[\"forgejo\"] | .container_name == \"forgejo\"'",
    "docker compose config --format json | jq --exit-status '.services[\"db\"] | .container_name == \"db\"'",
    "prek run --files ./*.*",
]

[output.".ctt/umami"]
use_umami = true
_post_tasks = [
    "docker compose config --format json | jq --exit-status '.services | length == 3'",
    "docker compose config --format json | jq --exit-status '.services[\"umami\"] | .container_name == \"umami\"'",
    "docker compose config --format json | jq --exit-status '.services[\"db\"] | .container_name == \"db\"'",
    "prek run --files ./*.*",
]

[output.".ctt/all"]
use_pihole = true
use_nextcloud = true
use_forgejo = true
use_umami = true
_post_tasks = [
    "docker compose config --format json | jq --exit-status '.services | length == 8'",
    # print volumes that don't have create_host_path = false set
    "docker compose config --format json | jq '[.services[].volumes[]? | select(.bind.create_host_path != false)]'",
    "docker compose config --format json | jq --exit-status '[.services[].volumes[]?] | all(.bind.create_host_path == false)'",
    "prek run --files ./*.*",
    # change pihole port to avoid conflicts in CI
    "sed -i.bak 's|\"53:53/|\"5353:53/|' compose.yaml",
    "docker compose up -d",
    "docker compose down",
]
