# https://copier-template-tester.kyleking.me/#configuration-file
# minimal defaults required to generate a project
[defaults]
_pre_tasks = [
    "tests/check_missing_envs.sh",
    "tests/check_missing_paths.sh",
]
letsencrypt_challenge = "tls"
letsencrypt_email = "foo@bar.baz"

[output.".ctt/defaults"]
_post_tasks = [
    "! ls .envs/letsencrypt.env",
    "! ls compose.*.yaml",
    "docker compose config --format json | jq --exit-status '.services | length == 1'",
    "docker compose config --format json | jq --exit-status '.services[\"traefik\"] | .container_name == \"traefik\"'",
]

[output.".ctt/dns_challenge"]
letsencrypt_challenge = "dns"
_post_tasks = [
    "ls .envs/letsencrypt.env",
    "docker compose config --format json | jq --exit-status '.services | length == 1'",
    "docker compose config --format json | jq --exit-status '.services[\"traefik\"] | .container_name == \"traefik\"'",
]

[output.".ctt/pihole"]
use_pihole = true
_post_tasks = [
    "docker compose config --format json | jq --exit-status '.services | length == 2'",
    "docker compose config --format json | jq --exit-status '.services[\"pihole\"] | .container_name == \"pihole\"'",
]

[output.".ctt/nextcloud"]
use_nextcloud = true
_post_tasks = [
    "docker compose config --format json | jq --exit-status '.services | length == 5'",
    "docker compose config --format json | jq --exit-status '.services[\"nextcloud\"] | .container_name == \"nextcloud\"'",
    "docker compose config --format json | jq --exit-status '.services[\"db\"] | .container_name == \"db\"'",
]

[output.".ctt/all"]
use_pihole = true
use_nextcloud = true
_post_tasks = [
    "docker compose config --format json | jq --exit-status '.services | length == 6'",
    "docker compose ps",
    "docker compose up -d",
    "docker compose down",
]
