name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        id: setup-uv
        with:
          # renovate: datasource=pypi dependency=uv
          version: "0.10.12"
      - uses: j178/prek-action@79f765515bd648eb4d6bb1b17277b7cb22cb6468 # v2.0.0
        with:
          # renovate: datasource=pypi dependency=prek
          prek-version: "0.3.6"
        env:
          SKIP: markdownlint-cli2
      - name: Run markdownlint
        if: '!cancelled()'
        env:
          # renovate: datasource=docker depName=davidanson/markdownlint-cli2-rules versioning=semver
          MARKDOWNLINT_CLI2_VERSION: v0.21.0
        # node user does not have permissions to workspace due to user id mismatch -> use root
        run: |
          docker run --rm \
          -v ${{ github.workspace }}:/workdir \
          --user root \
          davidanson/markdownlint-cli2-rules:${{ env.MARKDOWNLINT_CLI2_VERSION }} \
          markdownlint-cli2 --config .github/markdownlint/.markdownlint-cli2.yaml "**/*.md"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        id: setup-uv
        with:
          # renovate: datasource=pypi dependency=uv
          version: "0.10.12"
      - name: Test template using copier-template-tester
        run: |
          ./ctt.sh
